### ISSUE TITLE
Are tabs hidable

### ISSUE THREAD

**Issue by Luehrsen** [Freemius/wordpress-sdk#176]
**Actual Behavior**:
 -  `What is the issue? (*)`
The usability and reliability of the tabs are not good. We would like to hide them. 

 -  `What is the expected behavior?`
We want to have the ability to hide the tabs with a filter, a line of code or similar.

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.2.7
 -  `WordPress Version:` 4.8.1
 -  `PHP Version:` 7.1.0

**Plugin / Theme**: (*)
 -  `Name:` Agncy
 -  `Slug:` agncy
 -  `Freemius ID:` 1282

**Additional Information**:
 -  `Browser Type: (*)` Chrome 
 -  `Browser Version: (*)`  60.0.3112.90
 -  `OS: (*)` MacOS X / Mamp

**Comment by vovafeldman** [comment]
Hi @Luehrsen, I have a few follow-up questions:
1. Are you integrating Freemius into a theme?
2. Can you please explain what isn't reliable so we can try and fix it? (screenshot would be great)

**Comment by Luehrsen** [comment]
Hey @vovafeldman 

### 1 Yes, all my issues (if I haven't made it clear enough) are theme related.

### See these screenshots attached

![bildschirmfoto 2017-08-24 um 17 20 06](https://user-images.githubusercontent.com/1105871/29673832-a73701b8-88f0-11e7-9675-e1c894aa99df.png)
Double the account tabs, twice the fun. :) 

![bildschirmfoto 2017-08-24 um 17 20 25](https://user-images.githubusercontent.com/1105871/29673855-b523ed2c-88f0-11e7-90f8-59ea359ef4d1.png)
The contact tab doesn't go into active state.

![bildschirmfoto 2017-08-24 um 17 20 33](https://user-images.githubusercontent.com/1105871/29673876-c616d20c-88f0-11e7-8a52-8b2f0322f835.png)
The upgrade screen also doesn't have an active state. 

And we don't have a support forum.

**Comment by vovafeldman** [comment]
Thanks for the screenshots @Luehrsen - very helpful!

We fixed the issue with the duplicate tabs for the upcoming release, it was happening with theme's that don't have their own tabs. You can already try it here:
https://github.com/freemius/wordpress-sdk/tree/develop

I don't think that we've encountered the tabs active state bug though, can you kindly test it with the new release on your environment?

Question - is it going to be a premium only or a freemium theme?

**Comment by Luehrsen** [comment]
We are currently testing around with different models and are not that far into implementation. So no definite answer for premium vs. freemium. But the end goal is a freemium with trial approach. (Side note: the trial feature sold me on freemius.)

Will test with a new version later this week.

**Comment by vovafeldman** [comment]
@Luehrsen the reason I was asking is that if you go for freemium and want to leverage wp.org for the free version distribution, you are not allowed to have top level menu items, you can only have one submenu item under "Appearance." That's why we implemented the tabs navigation for themes. Also, my GitHub account has some issue that I'm not getting notifications on issue updates, so if you see that you're not getting a response, you can always ping us via support@freemius.com. Keep me posted.

And yes, [trials are indeed an extremely powerful tool](https://freemius.com/blog/trials-premium-wordpress-plugins-themes/) when selling freemium products, and I'm happy we invested into trials to offer the most extensive solution on that angle to attract devs like yourself :100:

**Comment by Luehrsen** [comment]
@vovafeldman The wp.org issue makes sense. I think I would rename this issue to "tab-reliability and duplicate tabs" or similar.
