### ISSUE TITLE
Child Theme Support broken upon change of state from free to premium (-premium suffix)

### ISSUE THREAD

**Issue by Luehrsen** [Freemius/wordpress-sdk#266]
**Actual Behavior**:
When designing a child theme upon a freemius theme it is required to define the theme folder slug for the parent theme in the stylesheet header of the child theme. (see https://codex.wordpress.org/Child_Themes)

It is expected behaviour in freemius that the folder name changes, but that makes it impossible to create a child theme that works in any state of the freemius theme. (free and premium)

**Versions**: (*)
 -  `Freemius SDK Version:` 2.1.2
 -  `WordPress Version:` 4.9
 -  `PHP Version:` 7.1

**Theme**: (*)
 -  `Name:` Agncy
 -  `Slug:` agncy
 -  `Freemius ID:` 1282

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)` 69.0.3497.100
 -  `OS: (*)` MacOS 10.14

**Comment by Luehrsen** [comment]
This is the check if the parent theme can be found, based upon the stylesheet header information.

https://github.com/WordPress/WordPress/blob/56c162fbc9867f923862f64f1b4570d885f1ff03/wp-includes/class-wp-theme.php#L342

**Comment by Luehrsen** [comment]
This is where the parent theme gets loaded in a child theme context.

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-theme.php#L370

**Comment by vovafeldman** [comment]
@fajardoleo please take a look at this one. I think that the easiest solution would be to tap to WP logic and make it search for the `-premium` folder when running the premium theme version. I'm not sure if that's possible, but if it is, that's probably the easiest for now.

**Comment by fajardoleo** [comment]
Hi @Luehrsen, please check this out and let us know if it resolves the issue:
https://github.com/Freemius/wordpress-sdk/pull/268

If it doesn't work at first, please switch to a different theme then switch back to the child theme.

**Comment by vovafeldman** [comment]
@Luehrsen do you have control of the child theme? Can we propose a fix by adding code to the child theme?

Otherwise, due to the way child themes are loaded, if there are no plugins that running the Freemius SDK, the only option that will make it work is if the user will first activate the parent theme (to manipulate the core mechanism that identifies the relevant parent template), and only then switch to the child. Also, if the child theme will be later switched to a different theme (without Freemius), after 30 min (that's when the cache expires), WP will show an error that the child's parent theme is missing.

**Comment by Luehrsen** [comment]
@vovafeldman In our case, yes, we have control. 

In general, if you have a successful theme with freemius integration this will be an issue. Third party developers and integrators developing a child-theme for a freemius theme will sooner or later run into this issue and have a bad experience. 

So as for me, no immediate action has to be taken, but in general, this issue should be explored and fixed.

**Comment by Luehrsen** [comment]
Commit #268 does not solve the issue. 

![bildschirmfoto 2018-10-15 um 12 43 45](https://user-images.githubusercontent.com/1105871/46946438-04347600-d078-11e8-855a-856794f68452.png)

**Comment by vovafeldman** [comment]
@Luehrsen can you please give it another try. First activate the parent theme, and only then switch to the child theme. The order is important. Lmk if that worked.

P.S. We understand that we can't require that sequence execution from users, that's why I asked if it would be possible to add some code to the child theme instead of the SDK. I first want to make sure that the fix also works on your end.
