### ISSUE TITLE
If the user skip the opt-in then the SDK doesnt return the plan

### ISSUE THREAD

**Issue by juanobrach** [Freemius/wordpress-sdk#484]
# 🐞 bug report

**Behavior**:
 -  `I I am trying to use the get_plan method but it only responds as desired if the user accepts the activation opt-in.
That is, if the user does not accept the activation opt-in, the method always returns false.`
  A clear and concise description of the problem including reproduction steps when possible...
 -  `What I need is that once the user activates my plugin, access this method and recognize what type of license they have. So be it free, personal or any without depending on whether or not the user has to have accepted the freemius opt-in when activating.
I estimate that many users will not accept the opt-in and this becomes a fatal error for my plugin if I am not able to read what license it has.`
 

**Versions**: (*)
 -  `Freemius SDK Version:`  2.4.2
 -  `WordPress Version:`  5.4.4
 -  `PHP Version:`  7..2.18

**Plugin / Theme**: (*)
 -  `Name:`  Payment Page
 -  `Slug:`  payment-page
 -  `Freemius ID:`  6031

**Comment by vovafeldman** [comment]
@juanobrach for `get_plan()` to properly work the user has to either activate a license key or opt-in. If none of those have happened, there's no way how the SDK can guess what's the plan of the user simply because there's no connection between the Freeimus SDK to the API as the user didn't give their consent and "phoning home" is prohibited.
