### ISSUE TITLE
Fatal error on deleting free version with paid activated

### ISSUE THREAD

**Issue by shramee** [Freemius/wordpress-sdk#73]
Getting a white page (fatal) error on deleting the free version of plugin when it's paid version is active.

**Comment by vovafeldman** [comment]
@shramee we are having trouble reproducing the issue. Can you please share the error you are getting? If there's a stack trace, even better.

CC: @fajardoleo

**Comment by vovafeldman** [comment]
**Documentation:**
- The reason this is happening is because FS registers an uninstall hook for the free plugin version. 
- This trigger inclusion of the free plugin on deletion.
- Since pootle's main class is already defined in the premium plugin, the inclusion of the free version throws a fatal error.

**Solution:**
- Make sure that if one of the plugin versions (free or premium) is active, remove the uninstall hook.
